name: fatvo_uz
description: "Busmillah!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  step_progress_indicator: ^1.0.2
  flutter_islamic_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  flutter_bloc: ^8.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.15
  file_picker: ^5.0.1
  geolocator: ^9.0.0
  geocoding: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
